// Shared Products Database - Used across all pages
const allProductsData = {
  // Deal Products
  deal1: {
    id: "deal1",
    name: "Marvel Spiderman Action Figure Collectible Toy",
    images: [
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
      "images/webp/spiderman.webp",
    ],
    currentPrice: 24.99,
    originalPrice: 39.99,
    discount: 38,
    rating: 4.0,
    reviews: 234,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    flashDealHours: 5,
    stock: 50,
    description:
      "Marvel's iconic Spider-Man comes to life in this highly detailed action figure. Perfect for collectors and fans alike, this figure features multiple points of articulation for dynamic posing. Made with premium materials and attention to detail, this collectible brings the web-slinger right into your home.",
    features: [
      "Highly detailed sculpting",
      "Multiple points of articulation",
      "Premium quality materials",
      "Authentic movie design",
      "Includes display stand",
    ],
    specifications: {
      Brand: "Marvel",
      "Character Family": "Spider-Man",
      "Item Dimensions": "6 x 3 x 9 inches",
      Weight: "0.5 pounds",
      "Age Range": "4 years and up",
      Material: "PVC Plastic",
      Color: "Red/Blue",
    },
    category: "Action Figures",
  },
  deal2: {
    id: "deal2",
    name: "Labubu Limited Edition Collectible Figurine – Exclusive Designer Art Toy",
    images: ["images/webp/labubu.webp", "images/webp/labubu.webp", "images/webp/labubu.webp"],
    currentPrice: 49.99,
    originalPrice: 89.99,
    discount: 44,
    rating: 4.8,
    reviews: 512,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    flashDealHours: 1,
    stock: 25,
    description:
      "Own a piece of contemporary art with this limited edition Labubu figurine. This exclusive designer toy features the signature mischievous smile and unique character design that has captured hearts worldwide. Perfect for collectors and art toy enthusiasts.",
    features: [
      "Limited edition release",
      "Exclusive designer collaboration",
      "Premium collectible quality",
      "Comes with authenticity certificate",
      "Perfect for display",
    ],
    specifications: {
      Brand: "The Monsters",
      Designer: "Kasing Lung",
      "Item Dimensions": "2.5 x 2.5 x 6 inches",
      Weight: "0.3 pounds",
      Material: "PVC/ABS",
      Edition: "Limited Edition",
      Color: "Various",
    },
    category: "Designer Toys",
  },
  deal3: {
    id: "deal3",
    name: "DJI Mini Drone with 6K Ultra HD Camera and Smart Features",
    images: ["images/webp/drone-6.webp", "images/webp/drone-1.webp", "images/webp/drone-2.webp", "images/webp/drone-3.webp"],
    currentPrice: 129.99,
    originalPrice: 189.99,
    discount: 32,
    rating: 4.7,
    reviews: 30,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    flashDealHours: 8,
    stock: 15,
    description:
      "Experience flight like never before with the DJI Mini Drone featuring 6K Ultra HD camera capabilities. This compact drone packs professional-grade features into a lightweight, portable design. Perfect for aerial photography, videography, and recreational flying.",
    features: [
      "6K Ultra HD Camera",
      "3-Axis Gimbal Stabilization",
      "31 minutes flight time",
      "Smart return to home",
      "GPS positioning",
    ],
    specifications: {
      Brand: "DJI",
      "Camera Resolution": "6K Ultra HD",
      "Flight Time": "31 minutes",
      Weight: "249g",
      "Max Speed": "57 km/h",
      "Transmission Range": "10 km",
      Battery: "2250 mAh",
    },
    category: "Drones",
  },
  deal4: {
    id: "deal4",
    name: "Barbie Dreamhouse Doll Set",
    images: ["images/webp/barbie.webp", "images/webp/barbie-2.webp", "images/webp/barbie-brand.webp"],
    currentPrice: 179.99,
    originalPrice: 249.99,
    discount: 28,
    rating: 4.5,
    reviews: 90,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    flashDealHours: 1,
    stock: 30,
    description:
      "Step into the world of Barbie with this magnificent Dreamhouse doll set. Featuring multiple rooms, accessories, and endless possibilities for imaginative play. This iconic playset brings dreams to life with its stunning design and interactive features.",
    features: [
      "Multiple rooms and floors",
      "Includes furniture and accessories",
      "Working elevator",
      "Pool and slide",
      "Over 70 accessories",
    ],
    specifications: {
      Brand: "Barbie",
      "Product Dimensions": "45 x 14 x 39 inches",
      Weight: "28 pounds",
      "Age Range": "3 years and up",
      "Number of Pieces": "75+",
      Material: "Plastic",
    },
    category: "Dolls",
  },

  // Frequently Bought Products
  product1: {
    id: "product1",
    name: "Naruto Shippuden - Naruto Uzumaki - The Jinchuriki Entrusted with Hope, Bandai Spirits S.H.Figuarts Action Figure",
    images: ["images/webp/naruto.webp", "images/webp/naruto.webp", "images/webp/naruto.webp"],
    currentPrice: 2300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 127,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 40,
    description:
      "Bring the power of the Nine-Tails to your collection with this highly detailed Naruto Uzumaki action figure from Bandai Spirits' S.H.Figuarts line. This premium figure captures Naruto in his iconic orange jumpsuit with incredible articulation and includes multiple interchangeable parts for dynamic posing.",
    features: [
      "Highly articulated for dynamic poses",
      "Multiple interchangeable hands and faces",
      "Includes signature accessories",
      "Premium Bandai quality",
      "Display stand included",
    ],
    specifications: {
      Brand: "Bandai Spirits",
      Series: "S.H.Figuarts",
      Character: "Naruto Uzumaki",
      Height: "5.5 inches",
      Material: "ABS, PVC",
      "Age Range": "15 years and up",
    },
    category: "Action Figures",
  },
  product2: {
    id: "product2",
    name: "MoShow MCT_AP04 Noble Class Progenitor Effect Wei Guogong Mecha 04",
    images: [
      "images/webp/shoes.png", // placeholder
      "images/webp/shoes.png",
    ],
    video: "video/moshow.mp4",
    currentPrice: 2300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 127,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 20,
    description:
      "Experience the ultimate in mecha collectibles with the MoShow Noble Class Progenitor Effect Wei Guogong. This premium transformable figure features intricate details, LED effects, and premium die-cast metal construction. A must-have for serious mecha collectors.",
    features: [
      "Die-cast metal construction",
      "LED light effects",
      "Highly articulated joints",
      "Premium paint applications",
      "Includes multiple weapons",
    ],
    specifications: {
      Brand: "MoShow",
      Series: "Noble Class",
      Height: "12 inches",
      Weight: "2.5 pounds",
      Material: "Die-cast Metal, ABS, PVC",
      Scale: "1/72",
    },
    category: "Mecha Models",
  },
  product3: {
    id: "product3",
    name: "Dragon Ball Z Super Saiyan Son Goku 6.5-inch Action Figure Model Toy Gift",
    images: ["images/webp/goku.webp", "images/webp/goku.webp", "images/webp/goku.webp"],
    currentPrice: 300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 89,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 60,
    description:
      "Power up your collection with this Super Saiyan Son Goku action figure. Featuring the iconic golden hair and battle-ready stance, this figure captures Goku at his most powerful. Perfect for Dragon Ball Z fans and collectors.",
    features: [
      "Super Saiyan transformation",
      "Multiple articulation points",
      "Detailed sculpting",
      "Display base included",
      "Collectible quality",
    ],
    specifications: {
      Brand: "Dragon Ball Z",
      Character: "Son Goku",
      Height: "6.5 inches",
      Material: "PVC",
      "Age Range": "4 years and up",
      Form: "Super Saiyan",
    },
    category: "Action Figures",
  },
  product4: {
    id: "product4",
    name: "LEGO Classic Large Creative Brick Box 10698 Building Toy Set, Toy Storage Solution",
    images: ["images/webp/lego-classic.webp", "images/webp/lego.webp", "images/webp/batman-lego.webp"],
    currentPrice: 300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 245,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 100,
    description:
      "Unlock endless creativity with the LEGO Classic Large Creative Brick Box. With 790 pieces in 33 different colors, this set provides hours of building fun. Includes doors, windows, wheels, eyes, and more to bring your creations to life.",
    features: [
      "790 LEGO pieces",
      "33 different colors",
      "Includes special elements",
      "Storage box included",
      "Endless building possibilities",
    ],
    specifications: {
      Brand: "LEGO",
      "Piece Count": "790 pieces",
      "Age Range": "4-99 years",
      "Item Dimensions": "14.88 x 9.1 x 7.52 inches",
      Weight: "3.64 pounds",
      Model: "10698",
    },
    category: "Building Toys",
  },
  product5: {
    id: "product5",
    name: "LEGO ONE Piece Windmill Village Hut Building Blocks - Pretend Play Building Toy for Boys & Girls, Ages 8+",
    images: ["images/webp/lego-one-piece.webp", "images/webp/lego-one-piece.webp", "images/webp/lego.webp"],
    currentPrice: 300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 312,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 45,
    description:
      "Set sail for adventure with this LEGO One Piece Windmill Village Hut set. Recreate iconic scenes from the beloved anime series with this detailed building set. Features multiple characters and accessories from the One Piece universe.",
    features: [
      "Official LEGO x One Piece collaboration",
      "Includes mini-figures",
      "Detailed village hut design",
      "Multiple accessories",
      "Display-ready build",
    ],
    specifications: {
      Brand: "LEGO",
      Theme: "One Piece",
      "Piece Count": "456 pieces",
      "Age Range": "8 years and up",
      "Item Dimensions": "10.32 x 7.52 x 2.78 inches",
      Weight: "1.5 pounds",
    },
    category: "Building Toys",
  },
  product6: {
    id: "product6",
    name: "DJI Mini 4K, Drone with 4K UHD Camera for Adults, Under 249 g, 3-Axis Gimbal",
    images: ["images/webp/drone-1.webp", "images/webp/drone-2.webp", "images/webp/drone-3.webp", "images/webp/drone-4.webp"],
    currentPrice: 300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 156,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 25,
    description:
      "Capture stunning aerial footage with the DJI Mini 4K drone. Weighing under 249g, this compact drone doesn't require FAA registration in most countries. Features a 3-axis gimbal for smooth, stable video and photos.",
    features: [
      "4K UHD Camera",
      "3-Axis Gimbal",
      "Under 249g lightweight design",
      "31 min max flight time",
      "10km video transmission",
    ],
    specifications: {
      Brand: "DJI",
      "Camera Resolution": "4K/30fps",
      Weight: "Under 249g",
      "Flight Time": "31 minutes",
      "Max Speed": "16 m/s",
      "Transmission Range": "10 km",
      Battery: "2453 mAh",
    },
    category: "Drones",
  },
  product7: {
    id: "product7",
    name: "Barbie The Movie Doll, Margot Robbie as, Collectible Doll Wearing Gingham Dress with Daisy Chain Necklace",
    images: ["images/webp/barbie-2.webp", "images/webp/barbie.webp", "images/webp/barbie-brand.webp"],
    currentPrice: 300,
    originalPrice: null,
    discount: 0,
    rating: 4.0,
    reviews: 156,
    condition: "New",
    seller: "ETA07",
    sellerFeedback: 21671,
    sellerRating: 99.2,
    stock: 50,
    description:
      "Inspired by the Barbie Movie, this collectible doll captures Margot Robbie's iconic look. Featuring a beautiful gingham dress and daisy chain necklace, this premium doll is perfect for collectors and fans of the blockbuster film.",
    features: [
      "Official Barbie Movie merchandise",
      "Margot Robbie likeness",
      "Detailed gingham dress",
      "Daisy chain necklace included",
      "Premium collectible quality",
    ],
    specifications: {
      Brand: "Barbie",
      "Product Line": "Barbie The Movie",
      Height: "12 inches",
      "Age Range": "6 years and up",
      Material: "Plastic",
      "Package Dimensions": "12.75 x 6 x 2.5 inches",
    },
    category: "Dolls",
  },
};

// Export for use in other scripts
if (typeof module !== "undefined" && module.exports) {
  module.exports = { allProductsData };
}
